/** Stable slug → official state name (36 states + FCT). */
export const NIGERIA_STATES: Record<string, string> = {
  abia: "Abia",
  adamawa: "Adamawa",
  akwa_ibom: "Akwa Ibom",
  anambra: "Anambra",
  bauchi: "Bauchi",
  bayelsa: "Bayelsa",
  benue: "Benue",
  borno: "Borno",
  cross_river: "Cross River",
  delta: "Delta",
  ebonyi: "Ebonyi",
  edo: "Edo",
  ekiti: "Ekiti",
  enugu: "Enugu",
  fct: "Federal Capital Territory",
  gombe: "Gombe",
  imo: "Imo",
  jigawa: "Jigawa",
  kaduna: "Kaduna",
  kano: "Kano",
  katsina: "Katsina",
  kebbi: "Kebbi",
  kogi: "Kogi",
  kwara: "Kwara",
  lagos: "Lagos",
  nasarawa: "Nasarawa",
  niger: "Niger",
  ogun: "Ogun",
  ondo: "Ondo",
  osun: "Osun",
  oyo: "Oyo",
  plateau: "Plateau",
  rivers: "Rivers",
  sokoto: "Sokoto",
  taraba: "Taraba",
  yobe: "Yobe",
  zamfara: "Zamfara",
};

/** Official Nigeria state / FCT labels, sorted A–Z. */
export const NIGERIA_STATE_LABELS = Object.values(NIGERIA_STATES).sort((a, b) =>
  a.localeCompare(b),
);
